# Generated by Django 5.2.16 on 2026-08-04 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardapio', '0001_initial'),
        ('core', '0002_seed_formas_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormacaoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('margem_lucro_desejada_percentual', models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='Margem de lucro desejada (%)')),
                ('margem_premium_extra_percentual', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='Margem premium extra (%)')),
                ('preco_minimo', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Preço mínimo (R$)')),
                ('preco_ideal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Preço ideal (R$)')),
                ('preco_premium', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Preço premium (R$)')),
                ('preco_praticado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço praticado (R$)')),
                ('forma_pagamento_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.formapagamento', verbose_name='Forma de pagamento de referência (para simular taxa)')),
                ('item_cardapio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formacao_preco', to='cardapio.itemcardapio', verbose_name='Item do cardápio')),
            ],
            options={
                'verbose_name': 'Formação de Preço',
                'verbose_name_plural': 'Formação de Preços',
            },
        ),
    ]
