# Generated by Django 5.2.16 on 2026-08-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formacaopreco',
            options={'ordering': ['item_cardapio__nome'], 'verbose_name': 'Formação de Preço', 'verbose_name_plural': 'Formação de Preços'},
        ),
    ]
