# Generated by Django 5.2.16 on 2026-08-04 13:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precificacao', '0002_alter_formacaopreco_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacaopreco',
            name='margem_lucro_desejada_percentual',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Margem de lucro desejada (%)'),
        ),
        migrations.AlterField(
            model_name='formacaopreco',
            name='margem_premium_extra_percentual',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('99.99'))], verbose_name='Margem premium extra (%)'),
        ),
        migrations.AlterField(
            model_name='formacaopreco',
            name='preco_praticado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço praticado (R$)'),
        ),
    ]
