# Generated by Django 5.2.16 on 2026-08-04 13:08

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriacardapio',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='itemcardapio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='cardapio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.validar_tamanho_imagem], verbose_name='Foto'),
        ),
    ]
