# Generated by Django 5.2.16 on 2026-08-04 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_alter_categoriacardapio_nome_alter_itemcardapio_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcardapio',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='cardapio.categoriacardapio', verbose_name='Categoria'),
        ),
    ]
