# Generated by Django 5.2.16 on 2026-08-10 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_alter_itemcardapio_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço (R$)')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('categorias', models.ManyToManyField(blank=True, help_text='O adicional aparece automaticamente em todos os itens ativos destas categorias.', related_name='adicionais', to='cardapio.categoriacardapio', verbose_name='Categorias')),
                ('itens', models.ManyToManyField(blank=True, help_text='Disponibiliza o adicional também nestes itens específicos, mesmo que sejam de outra categoria.', related_name='adicionais_especificos', to='cardapio.itemcardapio', verbose_name='Itens específicos')),
            ],
            options={
                'verbose_name': 'Adicional',
                'verbose_name_plural': 'Adicionais',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
