# Generated by Django 5.2.16 on 2026-08-13 18:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0004_adicional'),
        ('estoque', '0005_ingrediente_rendimento_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicional',
            name='ingrediente',
            field=models.ForeignKey(blank=True, help_text='Ingrediente baixado do estoque a cada unidade vendida deste adicional. Deixe em branco para um adicional que não controla estoque próprio (ex.: "Ponto da carne").', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usos_em_adicionais', to='estoque.ingrediente', verbose_name='Ingrediente do estoque'),
        ),
        migrations.AddField(
            model_name='adicional',
            name='quantidade_ingrediente',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Quanto do ingrediente acima é consumido a cada unidade deste adicional, NA MESMA unidade de medida cadastrada no ingrediente (ex.: ingrediente em kg → informe em kg: 26 g de bacon = 0,026 kg). Somado ao que a receita do produto já consome desse ingrediente — nunca substitui.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'), message='A quantidade deve ser maior que zero.')], verbose_name='Quantidade consumida por unidade'),
        ),
        migrations.AlterField(
            model_name='adicional',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor cobrado do cliente por unidade do adicional. É independente do custo do ingrediente abaixo — mudar o custo do ingrediente nunca altera este preço automaticamente.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço de venda (R$)'),
        ),
    ]
