# Generated by Django 5.2.16 on 2026-08-19 16:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def migrar_tipo_simples_para_produzido(apps, schema_editor):
    """
    'simples' deixa de existir como choice de ItemCardapio.tipo (vira 'produzido' /
    'revenda' / 'combo') — todo item já cadastrado como 'simples' sempre teve o
    comportamento que agora chamamos de 'produzido' (o único que o sistema oferecia até
    aqui: custo/estoque vindos de uma Receita), então a migração de dados é uma
    inferência segura, sem perda de significado. Itens 'combo' não mudam de valor.
    """
    ItemCardapio = apps.get_model('cardapio', 'ItemCardapio')
    ItemCardapio.objects.filter(tipo='simples').update(tipo='produzido')


def reverter_tipo_produzido_para_simples(apps, schema_editor):
    """Reversão simétrica — só desfaz o que a migração de ida fez (produzido -> simples);
    'revenda' não existia antes desta migração, então não há para onde reverter um item
    que tenha sido criado como 'revenda' depois dela (fica como está, sem dado equivalente
    no schema antigo)."""
    ItemCardapio = apps.get_model('cardapio', 'ItemCardapio')
    ItemCardapio.objects.filter(tipo='produzido').update(tipo='simples')


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0005_adicional_ingrediente'),
        ('estoque', '0006_ingrediente_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcardapio',
            name='produto_revenda',
            field=models.ForeignKey(blank=True, help_text='Obrigatório quando o tipo é "Revenda". O ingrediente precisa ser do tipo "Produto de revenda" (cadastrado no Estoque). Cada unidade vendida baixa 1 unidade deste ingrediente, sem ficha técnica.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_cardapio_revenda', to='estoque.ingrediente', verbose_name='Produto de revenda vinculado'),
        ),
        migrations.RunPython(migrar_tipo_simples_para_produzido, reverter_tipo_produzido_para_simples),
        migrations.AlterField(
            model_name='itemcardapio',
            name='tipo',
            field=models.CharField(choices=[('produzido', 'Produzido'), ('revenda', 'Revenda'), ('combo', 'Combo')], default='produzido', help_text='Produzido: tem ficha técnica (hambúrguer, molho...). Revenda: comprado pronto, vendido inteiro, sem ficha técnica (Coca-Cola, água...). Combo: composto por outros itens do cardápio, com preço próprio.', max_length=10, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='ComboComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='cardapio.itemcardapio', verbose_name='Combo')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_em_combos', to='cardapio.itemcardapio', verbose_name='Item componente')),
            ],
            options={
                'verbose_name': 'Componente do Combo',
                'verbose_name_plural': 'Componentes do Combo',
                'ordering': ['id'],
                'unique_together': {('combo', 'componente')},
            },
        ),
    ]
