# Generated by Django 5.2.16 on 2026-08-04 12:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardapio', '0001_initial'),
        ('core', '0002_seed_formas_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número')),
                ('data_hora', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data/hora')),
                ('canal', models.CharField(choices=[('balcao', 'Balcão'), ('delivery', 'Delivery próprio'), ('ifood', 'iFood'), ('whatsapp', 'WhatsApp')], default='balcao', max_length=10, verbose_name='Canal')),
                ('status', models.CharField(choices=[('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='concluida', max_length=10, verbose_name='Status')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal (R$)')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto (R$)')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total (R$)')),
                ('custo_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Custo total (R$)')),
                ('comissao_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Comissão/taxa total (R$)')),
                ('lucro_bruto', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Lucro bruto (R$)')),
                ('lucro_liquido', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Lucro líquido (R$)')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.formapagamento', verbose_name='Forma de pagamento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Preço unitário (R$)')),
                ('custo_unitario', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Custo unitário (R$)')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Subtotal (R$)')),
                ('custo_subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Custo subtotal (R$)')),
                ('observacoes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('item_cardapio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_itens', to='cardapio.itemcardapio', verbose_name='Item do cardápio')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Item da Venda',
                'verbose_name_plural': 'Itens da Venda',
            },
        ),
    ]
