# Generated by Django 5.2.16 on 2026-08-04 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_alter_itemcardapio_categoria'),
        ('vendas', '0002_alter_itemvenda_quantidade_alter_venda_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='nome_produto_excluido',
            field=models.CharField(blank=True, help_text='Preenchido automaticamente quando o produto do cardápio é excluído após a venda ser cancelada.', max_length=150, verbose_name='Nome do produto (congelado)'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='item_cardapio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendas_itens', to='cardapio.itemcardapio', verbose_name='Item do cardápio'),
        ),
    ]
