# Generated by Django 5.2.16 on 2026-08-10 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0004_adicional'),
        ('vendas', '0003_itemvenda_nome_produto_excluido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='subtotal_adicionais',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal de adicionais (R$)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='cliente_nome',
            field=models.CharField(blank=True, help_text='Opcional. Usado apenas para identificação no pedido e na impressão da comanda.', max_length=150, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='venda',
            name='total_adicionais',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total de adicionais (R$)'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal produtos (R$)'),
        ),
        migrations.CreateModel(
            name='ItemVendaAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_adicional_excluido', models.CharField(blank=True, help_text='Preenchido automaticamente quando o adicional é excluído após a venda ser cancelada.', max_length=100, verbose_name='Nome do adicional (congelado)')),
                ('preco_unitario', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Preço unitário no momento da venda (R$)')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Subtotal (R$)')),
                ('adicional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usos_em_vendas', to='cardapio.adicional', verbose_name='Adicional')),
                ('item_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adicionais', to='vendas.itemvenda', verbose_name='Item da venda')),
            ],
            options={
                'verbose_name': 'Adicional do Item de Venda',
                'verbose_name_plural': 'Adicionais do Item de Venda',
            },
        ),
    ]
