# Generated by Django 5.2.16 on 2026-08-10 14:11
#
# Introduz o conceito de "pedido em aberto" (ver apps/vendas/services.py: abrir_pedido,
# editar_pedido_aberto, finalizar_pedido). Vendas já existentes no banco não são afetadas em
# significado: todas continuam com status='concluida'/'cancelada' como já estavam — só o novo
# choice 'aberto' passa a existir para vendas criadas a partir de agora pelo novo fluxo.
#
# Backfill: `data_conclusao` é uma inferência segura para vendas antigas, porque no modelo
# anterior a venda sempre nascia concluída na mesma hora do lançamento (`data_hora` já ERA o
# momento da conclusão). Não é possível inferir `data_cancelamento` de vendas já canceladas
# antes desta migration (não há registro de quando o cancelamento ocorreu), então essas linhas
# ficam com data_cancelamento=None — limitação de dados históricos documentada no README_DEV.md.

import django.db.models.deletion
from django.db import migrations, models


def preencher_data_conclusao_de_vendas_antigas(apps, schema_editor):
    Venda = apps.get_model('vendas', 'Venda')
    Venda.objects.filter(status='concluida', data_conclusao__isnull=True).update(data_conclusao=models.F('data_hora'))


def reverter_preenchimento(apps, schema_editor):
    # Não desfaz o backfill: reverter essa migration não deve apagar a inferência já feita, só
    # remover os campos (o que a reversão automática das AddField abaixo já cuida de fazer).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_nome_estabelecimento'),
        ('vendas', '0004_adicionais_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data/hora do cancelamento'),
        ),
        migrations.AddField(
            model_name='venda',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data/hora da conclusão do pagamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.formapagamento', verbose_name='Forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='concluida', max_length=10, verbose_name='Status'),
        ),
        migrations.RunPython(preencher_data_conclusao_de_vendas_antigas, reverter_preenchimento),
    ]
