# Generated by Django 5.2.16 on 2026-08-13 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_pedido_aberto'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvenda',
            name='custo_subtotal_adicionais',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Custo subtotal de adicionais (R$)'),
        ),
        migrations.AddField(
            model_name='itemvendaadicional',
            name='custo_subtotal',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Custo subtotal (R$)'),
        ),
        migrations.AddField(
            model_name='itemvendaadicional',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=10, verbose_name='Custo unitário no momento da venda (R$)'),
        ),
        migrations.AddField(
            model_name='itemvendaadicional',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, help_text='Quantas vezes este adicional foi escolhido por unidade do item (ex.: 2 = "Bacon x2").', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade'),
        ),
    ]
