# Generated by Django 5.2.16 on 2026-08-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('custo_embalagem_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo de embalagem padrão (R$)')),
                ('percentual_gas_energia', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Gás/energia (% sobre custo de ingredientes)')),
                ('percentual_mao_de_obra', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Mão de obra (% sobre custo de ingredientes)')),
                ('percentual_imposto_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Imposto padrão (%)')),
                ('margem_lucro_ideal_padrao', models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='Margem de lucro ideal padrão (%)')),
                ('margem_premium_extra_padrao', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='Margem premium extra padrão (%)')),
                ('alerta_aumento_preco_percentual', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Alertar quando preço subir mais que (%)')),
                ('meta_faturamento_diaria', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Meta de faturamento diária (R$)')),
                ('meta_faturamento_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Meta de faturamento mensal (R$)')),
            ],
            options={
                'verbose_name': 'Configuração Geral',
                'verbose_name_plural': 'Configuração Geral',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('taxa_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa/comissão (%)')),
                ('prazo_recebimento_dias', models.PositiveIntegerField(default=0, verbose_name='Prazo de recebimento (dias)')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'ordering': ['nome'],
            },
        ),
    ]
