# Generated by Django 5.2.16 on 2026-08-04 13:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_formas_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaogeral',
            name='alerta_aumento_preco_percentual',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alertar quando preço subir mais que (%)'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='custo_embalagem_padrao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Custo de embalagem padrão (R$)'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='margem_lucro_ideal_padrao',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99.99)], verbose_name='Margem de lucro ideal padrão (%)'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='margem_premium_extra_padrao',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99.99)], verbose_name='Margem premium extra padrão (%)'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='meta_faturamento_diaria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Meta de faturamento diária (R$)'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='meta_faturamento_mensal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Meta de faturamento mensal (R$)'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='percentual_gas_energia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Gás/energia (% sobre custo de ingredientes)'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='percentual_imposto_padrao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Imposto padrão (%)'),
        ),
        migrations.AlterField(
            model_name='configuracaogeral',
            name='percentual_mao_de_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Mão de obra (% sobre custo de ingredientes)'),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='taxa_percentual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taxa/comissão (%)'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_repr', models.CharField(blank=True, help_text='Snapshot do usuário, sobrevive à exclusão da conta.', max_length=150)),
                ('acao', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Edição'), ('DELETE', 'Exclusão'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FALHOU', 'Tentativa de login falhou')], max_length=15)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('objeto_pk', models.CharField(blank=True, max_length=50)),
                ('objeto_repr', models.CharField(blank=True, max_length=255)),
                ('detalhes', models.TextField(blank=True)),
                ('endereco_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-data_hora'],
            },
        ),
    ]
