# Generated by Django 5.2.16 on 2026-08-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_configuracaogeral_alerta_aumento_preco_percentual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='nome_estabelecimento',
            field=models.CharField(blank=True, help_text='Aparece no cabeçalho do pedido impresso na impressora térmica.', max_length=150, verbose_name='Nome do estabelecimento'),
        ),
    ]
