# Generated by Django 5.2.16 on 2026-09-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_nome_estabelecimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaogeral',
            name='data_inicio_operacao',
            field=models.DateField(blank=True, help_text='Vendas e despesas com data anterior a esta deixam de contar no dashboard e nos relatórios agregados (faturamento, lucro, comparativo mensal etc.) — continuam no banco e nas listagens normalmente, só somem dos números. Deixe em branco para não aplicar nenhum corte (comportamento de sempre, todo o histórico conta).', null=True, verbose_name='Data de início da operação'),
        ),
    ]
