# Generated by Django 5.2.16 on 2026-08-04 12:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Categoria de Ingrediente',
                'verbose_name_plural': 'Categorias de Ingredientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('AJUSTE', 'Ajuste'), ('PERDA', 'Perda'), ('QUEBRA', 'Quebra'), ('INVENTARIO', 'Inventário')], max_length=12, verbose_name='Tipo')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade')),
                ('quantidade_anterior', models.DecimalField(decimal_places=3, editable=False, max_digits=10, verbose_name='Estoque anterior')),
                ('quantidade_posterior', models.DecimalField(decimal_places=3, editable=False, max_digits=10, verbose_name='Estoque posterior')),
                ('lote', models.CharField(blank=True, max_length=60, verbose_name='Lote')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('motivo', models.CharField(blank=True, max_length=255, verbose_name='Motivo/observação')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, verbose_name='Documento de referência')),
                ('data_movimentacao', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Data da movimentação')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-data_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('unidade_medida', models.CharField(choices=[('g', 'Grama (g)'), ('kg', 'Quilograma (kg)'), ('ml', 'Mililitro (ml)'), ('l', 'Litro (l)'), ('un', 'Unidade (un)')], max_length=5, verbose_name='Unidade de medida')),
                ('estoque_atual', models.DecimalField(decimal_places=3, default=0, editable=False, max_digits=10, verbose_name='Estoque atual')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Estoque mínimo')),
                ('estoque_ideal', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Estoque ideal')),
                ('localizacao', models.CharField(blank=True, max_length=100, verbose_name='Localização')),
                ('validade_padrao_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Validade padrão após entrada (dias)')),
                ('custo_unitario_atual', models.DecimalField(decimal_places=4, default=0, editable=False, max_digits=12, verbose_name='Custo unitário atual (R$/unidade-base)')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredientes', to='estoque.categoriaingrediente', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'ordering': ['nome'],
            },
        ),
    ]
