# Generated by Django 5.2.16 on 2026-08-04 13:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='estoque_ideal',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque ideal'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='estoque_minimo',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque mínimo'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='validade_padrao_dias',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Validade padrão após entrada (dias)'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'), message='A quantidade deve ser maior que zero.')], verbose_name='Quantidade'),
        ),
    ]
