# Generated by Django 5.2.16 on 2026-08-06 17:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_ingrediente_estoque_ideal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='rendimento_unidades',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Só se aplica a ingredientes medidos em "Unidade (un)" e comprados inteiros, mas usados em pequenas porções (ex.: alface, cebola, limão) — quando não há como pesar cada uso. Informe quantas porções uma unidade comprada rende (ex.: 10). Com isso preenchido, a quantidade na Ficha Técnica passa a ser em "porções", e o sistema divide o custo da unidade comprada por esse número. Deixe em branco para o comportamento padrão (quantidade em unidades inteiras, kg, g, l ou ml).', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'), message='O rendimento deve ser maior que zero.')], verbose_name='Rendimento (porções por unidade comprada)'),
        ),
    ]
