# Generated by Django 5.2.16 on 2026-08-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_ingrediente_rendimento_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='tipo',
            field=models.CharField(choices=[('materia_prima', 'Matéria-prima'), ('revenda', 'Produto de revenda')], db_index=True, default='materia_prima', help_text='Matéria-prima: usado em fichas técnicas, receitas de produção e adicionais (ex.: pão, carne, bacon). Produto de revenda: comprado pronto e vendido inteiro, sem ficha técnica (ex.: Coca-Cola, água) — vinculado direto a um item do cardápio do tipo "Revenda", nunca usado dentro de uma receita.', max_length=15, verbose_name='Tipo'),
        ),
    ]
