# Generated by Django 5.2.16 on 2026-09-30 15:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_ingrediente_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='A quantidade não pode ser negativa.')], verbose_name='Quantidade'),
        ),
    ]
