# Generated by Django 5.2.16 on 2026-08-04 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=200, verbose_name='Razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, verbose_name='Nome fantasia')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ/CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('endereco_completo', models.TextField(blank=True, verbose_name='Endereço')),
                ('contato_nome', models.CharField(blank=True, max_length=150, verbose_name='Nome do contato')),
                ('prazo_entrega_dias', models.PositiveIntegerField(default=0, verbose_name='Prazo de entrega (dias)')),
                ('pedido_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pedido mínimo (R$)')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome_produto', models.CharField(max_length=200, verbose_name='Nome do produto (como o fornecedor chama)')),
                ('codigo_produto_fornecedor', models.CharField(blank=True, max_length=60, verbose_name='Código/SKU do fornecedor')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('unidade_embalagem', models.CharField(choices=[('kg', 'Quilograma (kg)'), ('g', 'Grama (g)'), ('l', 'Litro (l)'), ('ml', 'Mililitro (ml)'), ('un', 'Unidade (un)'), ('cx', 'Caixa (cx)'), ('pct', 'Pacote (pct)'), ('fardo', 'Fardo')], max_length=10, verbose_name='Unidade da embalagem')),
                ('quantidade_embalagem', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Quantidade na embalagem')),
                ('preco_embalagem', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço da embalagem (R$)')),
                ('frete', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frete (R$)')),
                ('data_cotacao', models.DateField(blank=True, null=True, verbose_name='Data da cotação')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('preferencial', models.BooleanField(default=False, verbose_name='Fornecedor preferencial')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='fornecedores.fornecedor', verbose_name='Fornecedor')),
                ('ingrediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ofertas', to='estoque.ingrediente', verbose_name='Ingrediente vinculado')),
            ],
            options={
                'verbose_name': 'Produto de Fornecedor',
                'verbose_name_plural': 'Produtos de Fornecedores',
                'ordering': ['nome_produto'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_embalagem', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço da embalagem (R$)')),
                ('frete', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frete (R$)')),
                ('preco_unitario_calculado', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Preço por unidade-base (R$)')),
                ('variacao_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Variação (%)')),
                ('data_registro', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Registrado em')),
                ('produto_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precos', to='fornecedores.produtofornecedor', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Histórico de Preço',
                'verbose_name_plural': 'Históricos de Preço',
                'ordering': ['-data_registro'],
            },
        ),
    ]
