# Generated by Django 5.2.16 on 2026-08-04 13:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='pedido_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pedido mínimo (R$)'),
        ),
        migrations.AlterField(
            model_name='produtofornecedor',
            name='frete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Frete (R$)'),
        ),
        migrations.AlterField(
            model_name='produtofornecedor',
            name='preco_embalagem',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='O preço deve ser maior que zero.')], verbose_name='Preço da embalagem (R$)'),
        ),
        migrations.AlterField(
            model_name='produtofornecedor',
            name='quantidade_embalagem',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'), message='A quantidade da embalagem deve ser maior que zero.')], verbose_name='Quantidade na embalagem'),
        ),
    ]
