# Generated by Django 5.2.16 on 2026-08-05 17:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_configuracaogeral_alerta_aumento_preco_percentual_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('ALUGUEL', 'Aluguel'), ('ENERGIA', 'Energia'), ('AGUA', 'Água'), ('INTERNET', 'Internet'), ('FORNECEDOR', 'Fornecedor'), ('SALARIOS', 'Salários'), ('IMPOSTOS', 'Impostos'), ('MARKETING', 'Marketing'), ('MANUTENCAO', 'Manutenção'), ('OUTROS', 'Outros')], db_index=True, default='OUTROS', max_length=15, verbose_name='Categoria')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='O valor deve ser maior que zero.')], verbose_name='Valor (R$)')),
                ('data_vencimento', models.DateField(db_index=True, verbose_name='Data de vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de pagamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], db_index=True, default='PENDENTE', max_length=10, verbose_name='Status')),
                ('credor', models.CharField(blank=True, help_text='Nome de quem recebe (fornecedor, locador, concessionária...). Opcional.', max_length=150, verbose_name='Fornecedor/Credor')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('recorrente', models.BooleanField(default=False, verbose_name='Despesa recorrente')),
                ('periodicidade_recorrencia', models.CharField(blank=True, choices=[('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal'), ('ANUAL', 'Anual')], max_length=10, verbose_name='Periodicidade')),
                ('despesa_origem', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_geradas', to='despesas.despesa', verbose_name='Gerada a partir de')),
                ('forma_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='core.formapagamento', verbose_name='Forma de pagamento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado por')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data_vencimento'],
            },
        ),
    ]
