# Generated by Django 5.2.16 on 2026-08-04 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardapio', '0001_initial'),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('rendimento_quantidade', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Rendimento')),
                ('rendimento_unidade', models.CharField(choices=[('porcao', 'Porção'), ('un', 'Unidade')], default='porcao', max_length=10, verbose_name='Unidade do rendimento')),
                ('tempo_preparo_minutos', models.PositiveIntegerField(default=0, verbose_name='Tempo de preparo (min)')),
                ('modo_preparo', models.TextField(blank=True, verbose_name='Modo de preparo')),
                ('custo_embalagem_especifico', models.DecimalField(blank=True, decimal_places=2, help_text='Deixe em branco para usar o valor padrão das configurações gerais.', max_digits=10, null=True, verbose_name='Custo de embalagem específico (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('item_cardapio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receita', to='cardapio.itemcardapio', verbose_name='Item do cardápio')),
            ],
            options={
                'verbose_name': 'Ficha Técnica',
                'verbose_name_plural': 'Fichas Técnicas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_em_receitas', to='estoque.ingrediente', verbose_name='Ingrediente')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='receitas.receita', verbose_name='Ficha técnica')),
            ],
            options={
                'verbose_name': 'Item da Ficha Técnica',
                'verbose_name_plural': 'Itens da Ficha Técnica',
                'ordering': ['id'],
                'unique_together': {('receita', 'ingrediente')},
            },
        ),
    ]
