# Generated by Django 5.2.16 on 2026-08-04 13:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreceita',
            name='quantidade',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'), message='A quantidade deve ser maior que zero.')], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='custo_embalagem_especifico',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixe em branco para usar o valor padrão das configurações gerais.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Custo de embalagem específico (R$)'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='rendimento_quantidade',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'), message='O rendimento deve ser maior que zero.')], verbose_name='Rendimento'),
        ),
    ]
