# Generated by Django 5.2.16 on 2026-08-06 17:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_ingrediente_rendimento_unidades'),
        ('receitas', '0002_alter_itemreceita_quantidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceitaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('rendimento_quantidade', models.DecimalField(decimal_places=3, default=1, help_text='Quanto esta receita produz, na mesma unidade de medida do ingrediente produzido (ex.: ingrediente em "l" → rendimento em litros; ingrediente em "un" com rendimento por porção configurado no Estoque → normalmente "1", pois a divisão em porções já é feita pelo cadastro do ingrediente).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'), message='O rendimento deve ser maior que zero.')], verbose_name='Rendimento')),
                ('modo_preparo', models.TextField(blank=True, verbose_name='Modo de preparo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ingrediente_produzido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receita_producao', to='estoque.ingrediente', verbose_name='Ingrediente produzido')),
            ],
            options={
                'verbose_name': 'Receita de Produção',
                'verbose_name_plural': 'Receitas de Produção',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemReceitaProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'), message='A quantidade deve ser maior que zero.')], verbose_name='Quantidade')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos_em_producoes', to='estoque.ingrediente', verbose_name='Ingrediente')),
                ('receita_producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='receitas.receitaproducao', verbose_name='Receita de produção')),
            ],
            options={
                'verbose_name': 'Item da Receita de Produção',
                'verbose_name_plural': 'Itens da Receita de Produção',
                'ordering': ['id'],
                'unique_together': {('receita_producao', 'ingrediente')},
            },
        ),
    ]
